version: 2.1
orbs:
  node: circleci/node@2.1.1
  twilio: circleci/twilio@0.0.1
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - twilio/sendsms:
        body: This is a sample custom message for this particular build
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify
