version: 2.1
orbs:
  node: circleci/node@2.1.1
  twilio: circleci/twilio@0.0.1
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      # - run: npm test
      - twilio/sendsms:
          body: Send SMS to twilio
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify
