version: 2.1
orbs:
  node: circleci/node@3.0.0
  twilio: circleci/twilio@0.0.1
  slack: circleci/slack@3.4.2
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - twilio/sendsms:
          body: Send SMS to twilio
      - twilio/alert:
          body: Send SMS for error
      - slack/notify:
          channel: technical-content
          color: '#42e2f4'
          mentions: 'yemiwebby,'
          message: This is a custom message notification
          webhook: https://hooks.slack.com/services/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
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify
