version: 2.1
orbs:
  node: circleci/node@2.1.1
  twilio: circleci/twililo@volatile
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      # - run: npm test
      - twilio/sendsms:
        body: This is a sample custom message for this particular build
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify
